### ISSUE TITLE
!talk command

### ISSUE THREAD

**Issue by ghost** [domino54/galaxybot#1]
Hello, talk command isn't working on me, it doesn't even reply.
Thanks for help

**Comment by domino54** [comment]
Hey! The `talk` command is available only through a direct conversation with the bot and only for the person specified in `config.yml` as `dommy`, who is me by default. ^^ If you're hosting a fork of my bot, change this setting in your config file - it's the ID of the user.

**Comment by ghost** [comment]
Yo'
When I change dommy in `config.yml` with my discord ID I'm getting this :

> An error has occured while executing the command. Please contact my creator if this problem persists! 
TypeError: command.galaxybot.talkChannel.send is not a function

**Comment by domino54** [comment]
Shouldn't happen, will fix. You have to use the `settalk` first, which tells the bot which channel it's supposed to send messages in.

**Comment by ghost** [comment]
Oh okay I make it work, I was using `#channel` to select but it didn't work so I used the channel ID.
Thanks for help, awesome bot :)
