### ISSUE TITLE
!play command

### ISSUE THREAD

**Issue by ghost** [domino54/galaxybot#2]
Heyo'

Im having an issue with the `play` command, I use` !play ytblink` when Im in a vocal channel and Im getting this error.

[https://i.imgur.com/sP40ocj.png](url)

Im using YouTube Data API v3, I guess its what I should use.

Would be great if someone can help me about this.
Zurydix

**Comment by domino54** [comment]
Hi, that's a quick response of mine!

It shouldn't happen with latest bot version.

Cheers 😄
